### ISSUE TITLE
index.bsi?

### ISSUE THREAD

**Issue by Ekaznae** [BSData/kingsofwar#15]
Not sure if you saw this @amis92 I will just repost it.

I think with the addition of all these new files the index.bsi needs updated too? They aren't showing up on http://battlescribedata.appspot.com/#/repos

**Comment by amis92** [comment]
Oh, ok wait. Now I see there happens to be some problem with this repo. Why are there two .gst files?
There should only be one in one repo. Otherwise auto-updater on appspot won't process it.

May I suggest you to pack all the old files into some zip and attach this zip to the latest release, and rename all of the files to not include 2E. Then, when there are only the new files in the repo, do the release.

**Comment by Ekaznae** [comment]
I didn't know that's how it worked! Apologies. I will get started on that right away.

**Comment by amis92** [comment]
Ok, now I've done the release, all should be set.
