### ISSUE TITLE
[Anon] Bug report: Abyssal Dwarfs.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kingsofwar#34]
**File:** Abyssal Dwarfs.catz

**BattleScribe version:** 2.00.23

**Platform:** Android

**Dropbox:** No

**Description:** When viewing the army list below in view mode, the Katsuchan rocket launcher's blast (n) description does not show up beneath its stats, so I do not know what to roll for its blast damage.
500pts roster. Regiment Immortal guard w/ mutated throwing mastiff and brew of haste. 2 troops decimators. Katsuchan rocket launcher.

**Comment by Ekaznae** [comment]
BattleScribe 2.0 defaults the view mode option "Minimal Output?" (might still be called "Length" on mobile devices) to Minimal. If you change this to Full, you can see all the old numerical values again! Unfortunately this doesn't solve the same problem with the little "preview popups" but those entries are visible in the main Roster Selection window as it is, so that's not quite as bothersome.
